name: Build and Push Docker Image

on:
  workflow_dispatch:      
  push:
    branches:
      - main1
      - develop1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from pom.xml
      id: version
      run: echo "::set-output name=version::$(xmllint --xpath 'string(/project/version)' pom.xml)"

    - name: Get short commit SHA
      id: vars
      run: echo "::set-output name=short_sha::${GITHUB_SHA::8}"

    - name: Build and push Docker image
      run: |
        docker build -t my-java-app:${{ steps.version.outputs.version }}-${{ steps.vars.outputs.short_sha }} .
        docker push my-java-app:${{ steps.version.outputs.version }}-${{ steps.vars.outputs.short_sha }}
