name: Webapp - Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' 
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Bump version and push tag
      id: version
      run: |
        NEW_VERSION=$(mvn release:prepare -DpushChanges=false -DautoVersionSubmodules=true | grep "Bumped revision" | awk '{print $5}')
        git push origin main --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.NEW_VERSION }}
        release_name: Release ${{ steps.version.outputs.NEW_VERSION }}
        body: |
          ## Changes
          - Describe your changes here.
        draft: false
        prerelease: false
