name: Deployment - Resuable Workflow

on: 
    workflow_call:

jobs:
    reuse-deploy:
        runs-on: ubuntu-latest    
        steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Update kubeconfig
          run: |
            aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --role-arn ${{ secrets.EKS_ROLE_ARN }}      
        - name: Deploy to EKS
          run: |
            kubectl apply -f manifestfiles
            kubectl apply -f manifestfiles
            kubectl apply -f manifestfiles
            kubectl apply -f manifestfiles