name: Deployment - Resuable Workflow

on: 
  workflow_call:
      secrets:
        aws_access_keyid:
          required: true
        aws_secret_accesskey:
          required: true 
        aws_region:
          required: true
        eks_cluster_name:
          required: true
        eks_role_arn:
          required: true 
        dockerhub_username:
          required: true   

jobs:
    reuse-deploy:
        runs-on: ubuntu-latest    
        steps:      
        - name: checkout Git repository
          uses: actions/checkout@v4      
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.aws_access_keyid }}
            aws-secret-access-key: ${{ secrets.aws_secret_accesskey }}
            aws-region: ${{ secrets.aws_region }}
        - name: Update kubeconfig
          run: |
            aws eks update-kubeconfig --name ${{ secrets.eks_cluster_name }} --region ${{ secrets.aws_region }}    
        
        - name: Display files before deploying
          run: |
            ls -lrta

        - name: Deploy to EKS
          run: |
            kubectl apply -f manifestfiles
            kubectl set image deployment/mywebapp-deployment webapp-container=${{ secrets.dockerhub_username }}/myweb-app-java:${{ github.run_id }}

            
